### ISSUE TITLE
בדיקת מטלה 2

### ISSUE THREAD

**Issue by michael-lemberger** [Ariel-Gamers/Vaccinated-or-Exterminated#1]
לא הצלחתי להבין בכלל איך המשחק אמור להראות. דמיינתי אותו בכמה דרכים. אולי כדאי שתנסו לדמות תהליך כלשהו במהלך המשחק?

**Comment by ItayMeiri** [comment]
קשה להמחיש את המשחק במילים, העיקרון הוא שאתה משחק את תפקידה של מערכת החיסון באופן אסטרטגי
:אריץ דוגמה להמחשה של שלב במשחק

ראשית, לשחקן יש כמות אנרגיה מוגבלת, אשר מתחדשת כל פרק זמן(למשל, 2 דק') 
עם האנרגיה הזו השחקן יכול "לבנות" תאים במערכת החיסון, לכל תא שכזה יש חולשה וחוזקה

**דוגמה:**
**נויטרופילים** חזקים כנגד חיידקים, חלשים כנגד טפילים ונגיפים
**תאי "הרג טבעי"** (לימפוציטים) חזקים מאוד כנגד נגיפים
**מקרופאגים** - מסיירים למציאת נגיפים/חיידקים

ככל שגורם מחלה נמצא בגוף יותר זמן, כך הוא גדל ונהייה מסוכן יותר

המשחק מתחיל כאשר הגוף בריא וללא תסמינים, תסמינים משפיעים על עלויות ויעילות התאים
כבר בהתחלה יש לחשוב כמה תאים מסיירים עלייך לבנות כדי למצוא תוקפים בשלב מוקדם

לאחר זמן קצר, מתגלה נגיף האחראי לצינון
צינון גורם לתסמינים אשר מפחיתים את האנרגיה המחודשת
הנגיף הגורם לצינון לא מתפשט מהר וקל להילחם בו - כלומר תא חיסון אחד יכול להשמיד המון נגיפים הגורמים לצינון

הערה: כל המידע אודות התוקף נמצא על המסך

נניח והשחקן החליט לבזבז את כל האנרגיה שלו על מנת לנצח את **הנגיף** במהרה
לפתע מתגלה זיהום דלקתי - הנגרם ע"י **חיידקים**

כיוון שבזבז את כל האנרגיה שלו, לא יכול לרכוש נויטרופילים, אשר מתמחים בלוחמה בחיידקים
עליו לחכות לחידוש האנרגיה, ובינתיים הנגיף מתפשט ומתעצם

כפי שאתה רואה, עליו לאזן את הוצאות האנרגיה שלו לפי הצרכים והסכנות

השחקן מנצח כאשר מצליח להביס את כל התקופים, או מפסיד כאשר הגוף מגיע לנקודה קריטית כלשהי

כל שלב קשה יותר מקודמו ובעל אפשרויות שונות ותנאי התחלה שונים

השחקן יכול גם לעשות בחירות חיצוניות אשר משפיעות על היכולות שלו

למשל - חיסון מאפשר יצירה של תאים לנגיף או חיידק מסוים באופן מיידי
תרופה נגד חום יכולה להפחית את חלק מהתסמינים באופן זמני

האפשרויות האלו מגיעות עם יתרונות וחסרונות
אנטיביוטיקה - עוזרת משמעותית כנגד חיידקים, אך גורמת לתסמינים שליליים אחרים
